name: SD Course Check
on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Set up JDK 11
              uses: actions/setup-java@v2
              with:
                  distribution: 'zulu'
                  java-version: '11'
            - name: Setup Gradle
              uses: gradle/gradle-build-action@v2
            - name: Check out repository code
              uses: actions/checkout@v2
            - name: Build with Gradle
              id: build
              run: ./gradlew build -x test -x detekt

            - name: Check style
              if: ${{ always() }}
              id: check_style
              run: ./gradlew detekt
            - name: Upload a linter report
              if: ${{ steps.check_style.conclusion == 'failure' }}
              uses: actions/upload-artifact@v2
              with:
                  name: linter-report
                  path: build/reports/detekt

            - name: Test with Gradle
              id: test
              if: ${{ steps.build.conclusion == 'success' }}
              run: ./gradlew test
            - name: Upload a test report
              if: ${{ steps.test.conclusion == 'failure' }}
              uses: actions/upload-artifact@v2
              with:
                  name: test-report
                  path: build/reports/tests/test
            - name: Check test coverage with Gradle
              if: ${{ always() }}
              run: ./gradlew jacocoTestCoverageVerification
            - name: Create a test coverage report
              if: ${{ always() }}
              id: coverage_report
              run: ./gradlew jacocoTestReport
            - name: Upload a test coverage report
              if: ${{ steps.coverage_report.conclusion == 'success' }}
              uses: actions/upload-artifact@v2
              with:
                  name: jacoco-html-report
                  path: build/jacocoHtml
